# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Hermione
tagline:             'storage room'
description:         'This is a storage room with all kinds of things. I hope you will like it.'
url:                 http://hermione521.github.io/
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Gan Yue
  url:               https://github.com/hermione521
  email:             hermione0521@gmail.com

# Custom vars
version:             1.0.0
